/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package base;

import java.awt.FlowLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JApplet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;  
import javax.swing.JButton;
import javax.swing.JFrame;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import com.mysql.cj.jdbc.Driver;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import javax.swing.SwingConstants;

/**
 *
 * @author Zids
 */
public class dashboard extends javax.swing.JFrame {
    int  addBalance;
    /**
     * Creates new form dashboard
     */
    private String strUsername;
    String loginUsn2;
    
    
    public String getLoginUsn2() {
        return loginUsn2;
    }

    public void setLoginUsn2(String loginUsn2) {
        this.loginUsn2 = loginUsn2;
        
    }

    
    
    public dashboard() {
        initComponents();
        this.strUsername = strUsername;
        output();
        
    }
    
    public void output(){
        //Connection con = DriverManager.getConnection("jdbc:mysql://localhost/dbakun", "root", "");
    // SELECT balance FROM tblakun WHERE username=loginUsn
        
        try (
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/dbakun", "root", "")) {
                //String showSql = "SHOW tbldata SELECT balance FROM username = ?";
                String showSql = "SELECT * balance FROM tbldata WHERE username = ?";
                //String showSql = "SHOW tblakun SELECT balance WHERE username =?";
            //"INSERT INTO seats2 (seat_num, is_booked) VALUES ('" + seatnum_txtfield.getText() + "', true)"
                PreparedStatement stmt = con.prepareStatement(showSql);

            // Set the parameter value for the username
                System.out.println("user dashboard: " + loginUsn2);    
                stmt.setString(1, loginUsn2);
                ResultSet resultSet = stmt.executeQuery(showSql);
                
            // Process the query results
            if (resultSet.next()) {
                // Retrieve balance from result set
              addBalance = resultSet.getInt("balance");
              outputDompet.setText(String.valueOf(addBalance));
              
                System.out.println("Balance: " + addBalance);
            } else {
                System.out.println("No data found for the given username.");
            }
        } catch (SQLException e) {
            // Handle exceptions appropriately
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error occurred: " + e.getMessage());
        } 

    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTransakasiDashboard = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        outputDompet = new javax.swing.JTextField();
        mainMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTransakasiDashboard.setBackground(new java.awt.Color(0,0,0,0));
        btnTransakasiDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransakasiDashboardActionPerformed(evt);
            }
        });
        getContentPane().add(btnTransakasiDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 230, 40));

        jButton3.setBackground(new java.awt.Color(0,0,0,0));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 400, 240, 40));

        jButton4.setBackground(new java.awt.Color(0,0,0,0));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 230, 40));

        jButton5.setBackground(new java.awt.Color(0,0,0,0));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 230, 40));

        jButton6.setBackground(new java.awt.Color(0,0,0,0));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 230, 40));

        outputDompet.setBackground(new java.awt.Color(0,0,0,0));
        outputDompet.setFont(new java.awt.Font("SimSun", 1, 48)); // NOI18N
        outputDompet.setForeground(new java.awt.Color(255, 255, 255));
        outputDompet.setBorder(null);
        outputDompet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputDompetActionPerformed(evt);
            }
        });
        getContentPane().add(outputDompet, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 290, 70));

        mainMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UiComponent/menu.png"))); // NOI18N
        getContentPane().add(mainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTransakasiDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransakasiDashboardActionPerformed
        //JOptionPane.showMessageDialog(this, "Berhasil");
        mainMenu.setVisible(false);
        this.dispose();
        new transaction().setVisible(true);
    }//GEN-LAST:event_btnTransakasiDashboardActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //JOptionPane.showMessageDialog(this, "Berhasil");
        mainMenu.setVisible(false);
        this.dispose();
        new loginPage().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //JOptionPane.showMessageDialog(this, "Berhasil");
        mainMenu.setVisible(false);
        this.dispose();
        new topUp().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //JOptionPane.showMessageDialog(this, "Berhasil");
        mainMenu.setVisible(false);
        this.dispose();
        new history().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //JOptionPane.showMessageDialog(this, "Berhasil");
        mainMenu.setVisible(false);
        this.dispose();
        new account().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void outputDompetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputDompetActionPerformed
            outputDompet.setHorizontalAlignment(SwingConstants.CENTER);
            outputDompet.setText(String.valueOf(addBalance));
            //outputDompet.setText(addBalance);
    }//GEN-LAST:event_outputDompetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                dashboard dash = new dashboard();
                dash.setVisible(true);
                loginPage log = new loginPage();
                String loginUsn2 = log.getStrUsername();
                dash.setLoginUsn2(loginUsn2);  
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTransakasiDashboard;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel mainMenu;
    private javax.swing.JTextField outputDompet;
    // End of variables declaration//GEN-END:variables
}
