/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package base;


import java.awt.FlowLayout;
import javax.swing.JApplet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import com.mysql.cj.jdbc.Driver;
import javax.swing.JButton;

/**
 *
 * @author Zids
 */
public class loginPage extends javax.swing.JFrame {
    Connection con = null;
    Statement st = null;
    private String strUsername;

    public String getStrUsername() {
        return strUsername;
    }

    public void setStrUsername(String strUsername) {
        this.strUsername = strUsername;
        strUsername = txtInputUser.getText();
    }

    /**
     * Creates new form loginPage
     */
    public loginPage() {
        initComponents();
        try {
       Class.forName("com.mysql.cj.jdbc.Driver");
          con = DriverManager.getConnection("jdbc:mysql://localhost/dbakun","root","");
            st = con.createStatement();
                            JOptionPane.showMessageDialog(null, "Alhamdulillah Berhasil Terkoneksi");
                }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Gagal terkoneksi Karena " + ex);
            System.out.println(ex);
        }
        
        setStrUsername(txtInputUser.getText());
    }
    
    public void hapuslayar(){
        txtInputUser.setText("");
        txtInputPass.setText("");
        }

    public JButton getBtnLogin() {
        return btnLogin;
    }
    
    public void cekLogin(){
       try{
            if(txtInputUser.getText().equals("") || txtInputPass.getText().equals("")){
                JOptionPane.showMessageDialog(rootPane, "Data Tidak Boleh Kosong", "Pesan", JOptionPane.ERROR_MESSAGE);
                txtInputUser.requestFocus();
                hapuslayar();
            }else{
                st = con.createStatement(); 
                    strUsername = txtInputUser.getText();
                    String sql = ("SELECT * FROM tbldata WHERE username='"+txtInputUser.getText()+"' AND password ='"+String.valueOf(txtInputPass.getPassword())+"'");
                    ResultSet rs = st.executeQuery(sql);
                    System.out.println("Username login : " + strUsername);
                    
                if(rs.next()){
                       login.setVisible(false);
                        this.dispose();
                        transaction transactionFrame = new transaction();
                        //dashboard dashboardFrame = new dashboard();
                        if (getStrUsername() != null) {
                        transactionFrame.setLoginUsn(getStrUsername()); // Set the value of loginUsn
                        //dashboardFrame.setLoginUsn2(getStrUsername());
    }       
                        
                        //dashboardFrame.setVisible(false);
                        transactionFrame.setVisible(true);
}
                else{
                    JOptionPane.showMessageDialog(rootPane, "UserName dan Password Salah\nAtau Akun Belum Terdaftar", "Pesan",
                    JOptionPane.ERROR_MESSAGE);
                    hapuslayar();
                }
            }
        }catch(Exception e){
            e.printStackTrace();
            }
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegister = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        new java.awt.Color(0,0,0,1);
        txtInputUser = new javax.swing.JTextField();
        txtInputPass = new javax.swing.JPasswordField();
        login = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegister.setBackground(new java.awt.Color(0,0,0,0));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 562, 60, 20));

        btnLogin.setBackground(new java.awt.Color(0,0,0,0));
        btnLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnLogin.setBorderPainted(false);
        btnLogin.setContentAreaFilled(false);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 120, 60));

        txtInputUser.setBackground(new java.awt.Color(0,0,0,0));
        txtInputUser.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        txtInputUser.setBorder(null);
        txtInputUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInputUserActionPerformed(evt);
            }
        });
        getContentPane().add(txtInputUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 230, 30));

        txtInputPass.setBackground(new java.awt.Color(0,0,0,0));
        txtInputPass.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        txtInputPass.setBorder(null);
        getContentPane().add(txtInputPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 402, 230, 30));

        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UiComponent/halamanLogin_1.png"))); // NOI18N
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtInputUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInputUserActionPerformed
        txtInputUser.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_txtInputUserActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        
            //        btnLogin.setOpaque(false);
            //        btnLogin.setContentAreaFilled(false);
            //        btnLogin.setBorderPainted(false);
        cekLogin();
            
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        JOptionPane.showMessageDialog(this, "Silahkan Register");
        login.setVisible(false);
        this.dispose();
        new signUp().setVisible(true);
    }//GEN-LAST:event_btnRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel login;
    private javax.swing.JPasswordField txtInputPass;
    private javax.swing.JTextField txtInputUser;
    // End of variables declaration//GEN-END:variables
}
