package base;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.FlowLayout;
import javax.swing.JApplet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import com.mysql.cj.jdbc.Driver;

/**
 *
 * @author Zids
 */
public class signUp extends javax.swing.JFrame {
    Connection con = null;
    Statement st = null;
    /**
     * Creates new form signUp
     */
    public signUp() {
        initComponents();

    }

    public void hapuslayar(){
        txtInputNewUser.setText("");
        txtInputNewEmail.setText("");
        txtCreatePass.setText("");
        }
    /**
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txtInputNewEmail = new javax.swing.JTextField();
        txtInputNewUser = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        txtCreatePass = new javax.swing.JPasswordField();
        daftar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0,0,0,0));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 542, 120, 60));

        txtInputNewEmail.setBackground(new java.awt.Color(0,0,0,0));
        txtInputNewEmail.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        txtInputNewEmail.setBorder(null);
        txtInputNewEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInputNewEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtInputNewEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 270, 30));

        txtInputNewUser.setBackground(new java.awt.Color(0,0,0,0));
        txtInputNewUser.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        txtInputNewUser.setBorder(null);
        txtInputNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInputNewUserActionPerformed(evt);
            }
        });
        getContentPane().add(txtInputNewUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 270, 30));

        jButton8.setBackground(new java.awt.Color(0,0,0,0));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 40, 50, 60));

        jPasswordField1.setBackground(new java.awt.Color(0,0,0,0));
        jPasswordField1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jPasswordField1.setBorder(null);
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, 270, 30));

        txtCreatePass.setBackground(new java.awt.Color(0,0,0,0));
        txtCreatePass.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        txtCreatePass.setBorder(null);
        getContentPane().add(txtCreatePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 412, 270, 30));

        daftar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UiComponent/registrasi.png"))); // NOI18N
        getContentPane().add(daftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtInputNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInputNewUserActionPerformed
        
    }//GEN-LAST:event_txtInputNewUserActionPerformed

    private void txtInputNewEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInputNewEmailActionPerformed
        
    }//GEN-LAST:event_txtInputNewEmailActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            if(txtInputNewUser.getText().equals("") || txtCreatePass.getPassword().equals("") ||
                    txtInputNewEmail.getText().equals("")){
                        JOptionPane.showMessageDialog(this, "Data TidaK Boleh Kosong", "Pesan", JOptionPane.ERROR_MESSAGE);
                hapuslayar();
                }else{
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    con=DriverManager.getConnection("jdbc:mysql://localhost/dbakun","root","");
                     st = con.createStatement();
                     String simpan = "INSERT INTO tbldata(username,password,email) VALUES('"+txtInputNewUser.getText()+ "','"+String.valueOf(txtCreatePass.getPassword())+ "','" 
                      +txtInputNewEmail.getText()+ "')";
                        st = con.createStatement();
                        st.executeUpdate(simpan);
                        JOptionPane.showMessageDialog(this, "Sign up berhasil, silahkan log in kembali");
                        this.setVisible(false);
                        daftar.setVisible(false);
                        this.dispose();
                        new loginPage().setVisible(true);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(this,"This Account is lready exist / Duplicate Account ", "Pesan",
                JOptionPane.WARNING_MESSAGE);
            System.out.println(e);
                    hapuslayar();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        daftar.setVisible(false);
        this.dispose();
        new loginPage().setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel daftar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton8;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField txtCreatePass;
    private javax.swing.JTextField txtInputNewEmail;
    private javax.swing.JTextField txtInputNewUser;
    // End of variables declaration//GEN-END:variables
}
